### ISSUE TITLE
Missing manifests

### ISSUE THREAD

**Issue by anomaly256** [vifino/vifino-overlay#10]
Hi, a lot of the package directories in this overlay appear to be missing Manifest files, preventing them from being installable without manually generating them after every sync

**Comment by vifino** [comment]
Yeah, you're correct.
Unfortunately, I do not have access to a gentoo machine at the moment, hardware died...

I would much appreciate you making a PR with the missing manifests, if you could be so kind.

**Comment by anomaly256** [comment]
Sure thing, will do this shortly
