### ISSUE TITLE
disputils ebuild no longer emerges

### ISSUE THREAD

**Issue by Jemi** [vifino/vifino-overlay#14]
Your disputils ebuild no longer emerges. Instead, it fails during compile phase with undefined references to xcb functions. Please see attached file.

[error.txt](https://github.com/vifino/vifino-overlay/files/2682869/error.txt)

**Comment by vifino** [comment]
Huh, that's weird. Seems like it doesn't link the XCB libraries?
Have you tried rebuilding xcb?

I currently do not have a Gentoo machine available. Machine broke.

**Comment by vifino** [comment]
I tried building disputils today on my modern Gentoo install.
Works fine for me.

**Comment by Jemi** [comment]
It works now for me. Not sure what the issue was. Maybe just a configuration issue.
