### ISSUE TITLE
Add python 3.7 python target to openrazer ebuild.

### ISSUE THREAD

**Issue by aTosser** [vifino/vifino-overlay#19]
I am testing python 3.7 on my system and polychromatic can not import any of the open razer stuff.

**Comment by vifino** [comment]
Sure, I'll commit something I think will work. You'll have to try it for me.

**Comment by aTosser** [comment]
These are the packages that would be merged, in order:

Calculating dependencies... done!

The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by app-misc/openrazer:0 (argument)
>=app-misc/openrazer-9999 -python_targets_python3_7

**Comment by aTosser** [comment]
Meh, not your problem. Some deps are do not have USE for python 3.7 time to go pester others. Cheers

**Comment by vifino** [comment]
You're welcome.
