### ISSUE TITLE
openrazer won't compile with kernel 5.4.0

### ISSUE THREAD

**Issue by ppfeufer** [vifino/vifino-overlay#22]
As per title and see build log

[build.log](https://github.com/vifino/vifino-overlay/files/3888756/build.log)

**Comment by JulienDlq** [comment]
Hello, I also have the same issue and same log.

**Comment by vifino** [comment]
Hey.
I could reproduce this with `pf-sources-5.4.0-pf1`, not sure why this happens, though.
I suspect the 5.4 release changed some behaviour in the Makefile, causing the `linux-mod` eclass's `linux-mod_src_install` to fail.
The `make` in question is not directly called by my ebuild.

I have little time, so I'm not sure I'll get around to doing more investigation.

**Comment by JulienDlq** [comment]
It seems to work since this merge, this issue can be closed. :grin:
