### ISSUE TITLE
app-misc/polychromatic: dev-python/distro dependency

### ISSUE THREAD

**Issue by JulienDlq** [vifino/vifino-overlay#24]
Now, app-misc/polychromatic needs dev-python/distro dependency.

Here is the commit from polychromatic: https://github.com/polychromatic/polychromatic/commit/493d5cb821b2b5f41f0cfba8e23d7f16cf170e9a

**Comment by vifino** [comment]
Thanks to @ppfeufer, this is fixed! Happy remerging!
