### ISSUE TITLE
udev files get installed into /usr/lib/udev results in nothing working

### ISSUE THREAD

**Issue by wschlich** [vifino/vifino-overlay#3]
Hi!

You razer-drivers-9999.ebuild installs all udev files into /usr/lib/udev instead of /lib/udev, so nothing udev-related is being executed, therefore nothing in total is working.
Can you please fix the ebuild to install all udev files /lib/udev instead?
Thanks!

Cheers,
Wolfram

**Comment by vifino** [comment]
Hello.

Good catch - would've probably not noticed for a while.
The issues stems from the `udev_install` being used, which is hardcoded to install /usr/lib/udev, I'll push a fix which should solve the problem.

**Comment by vifino** [comment]
Done - reemerge and report back? Should be OK now.
I am in no position to test now, unfortunately.

**Comment by wschlich** [comment]
Looks good:
```
zephyr ~ # qlist razer-drivers | grep /udev
/usr/lib/udev/razer_mount
/usr/lib/udev/rules.d/99-razer.rules
zephyr ~ # emerge razer-drivers &>/dev/null
zephyr ~ # qlist razer-drivers | grep /udev
/lib/udev/razer_mount
/lib/udev/rules.d/99-razer.rules
zephyr ~ # 
```

**Comment by vifino** [comment]
Lovely.

Thanks for reporting! :)
