### ISSUE TITLE
cant unmask openrazer ebuild

### ISSUE THREAD

**Issue by Eddy-Arch** [vifino/vifino-overlay#36]
![image](https://user-images.githubusercontent.com/58888419/88479934-47f12a80-cf42-11ea-8451-dc5b886c971d.png)

**Comment by ppfeufer** [comment]
```bash
echo "app-misc/openrazer ~amd" >> /etc/portage/package.accept_keywords/app-misc
```
That should do the trick

**Comment by vifino** [comment]
Hey.

> ```shell
> echo "app-misc/openrazer ~amd" >> /etc/portage/package.accept_keywords/app-misc
> ```
> 
> That should do the trick

Shouldn't that be `~amd64` if the person is running an x86_64 machine? Anyhow, `**` should always work.
