### ISSUE TITLE
lessc dependency breaks Polychromatic ebuild

### ISSUE THREAD

**Issue by evanjs** [vifino/vifino-overlay#4]
Polychromatic adds a dependency to lessc in [cff4b080a244887c704971c2d0527040f57f2137d](https://github.com/lah7/polychromatic/commit/ff4b080a244887c704971c2d0527040f57f2137d).
No longer builds, but compiles fine with a less compiler installed.
[dev-lang/less](https://gpo.zugaina.org/dev-lang/less) (eva overlay) is one of the few examples I could find on Zugaina.

**Comment by vifino** [comment]
Damn. I dislike javascript/nodejs/npm stuff.

Depending on something across overlays is a big no-no, so I'd need to include an ebuild for less here. Boo. 👎 

Do you know if https://github.com/BramvdKroef/clessc works as an alternative? Wouldn't require nodejs, which would be a big plus for me.

**Comment by Evanjs** [comment]
Not quite, it seems.
Seems to compile fine, but the controller looks pretty messed up. 

dev-lang/less
![screenshot_20170924_002134](https://user-images.githubusercontent.com/1847524/30779431-b770fa58-a0be-11e7-8a4f-f10f434ba1ca.png)

dev-cpp/clessc
![screenshot_20170924_002343](https://user-images.githubusercontent.com/1847524/30779432-b77167d6-a0be-11e7-8271-8a00c05faa74.png)

Going to assume it has something to do with the features clessc supports, but I honestly have no idea.

**Comment by vifino** [comment]
Damn, that is a shame.  Guess there is no way around it.

The reason I don't really wanna do it with the javascript one is because it depends on nodejs, which is a pain to get working/compiling decently with LibreSSL, but oh well.

I'll take a look at making a less ebuild and marking it as a dependency soon. May not be today or tomorrow, I unfortunately am quite busy at the moment. It will be done eventually, however.

If you do want to help, I'd gladly appreciate it. :)

**Comment by Evanjs** [comment]
Emerging [nodejs-8.1.0](https://github.com/gentoo/libressl/blob/11777ddb2be6e1d7b3dae987b7033ca0886584b1/net-libs/nodejs/nodejs-8.1.0.ebuild) from libressl overlay (first ebuild in there that doesn't hack openssl in when using libressl) and [less-1.3.3](https://github.com/gentoo-mirror/eva/blob/master/dev-lang/less/less-1.3.3.ebuild) from eva seems to work fine.

I just wonder how much work it would take to get the node ebuild to work with openssl _and_ libressl.
Though, if that's not a concern, I wonder if this would be enough.

**Comment by vifino** [comment]
Sorry for my late reply. I've had basically no time.

Since upstream has a nodejs ebuild, we can depend on that, libressl's overlay just replaces it.

I'll try to make a less ebuild for my overlay soon, since I don't want to require another overlay to be installed.
No timeline promises, other than that I won't forget this issue. It's on my todo list.

**Comment by bcoca** [comment]
tried using dev-python/lesscpy instead but it cannot process the .less file.

**Comment by vifino** [comment]
Welp, I guess I gotta surrender for the greater good.

I'll add the (original, nodejs) less dependency as soon as I fix two other small issues.

**Comment by vifino** [comment]
Yeah, the whole thing got lost on my TODO list. Busy times.

Since a lot of time passed, clessc might be able to work now. The [clessc repo](https://github.com/BramvdKroef/clessc) has a lot of changes since then.

I need to set up a new Gentoo install, since the last one died due to hardware failure and I took the chance to install FreeBSD instead.
Adding an ebuild for clessc and adding a dependency to the Polychromatic ebuild is pretty trivial.

With some luck, I'll find time rather soon. If you (or someone else) tests the latest clessc with ebuild, I could write the ebuild changes quite quickly.

**Comment by llitz** [comment]
Just tried it, the output is better but still not quite there. Also, cless isn't a drop-in replacement you need to create a wrapper doing 'clessc "${1}" > "${2}"'

Checking clessc repo I can not all features have been implemented yet, we are probably lacking some of these or we have a bug on one of the others.

**Comment by vifino** [comment]
I'd highly appreciate a PR! That way I don't have to write a less ebuild and users don't have to use more overlays.

**Comment by vifino** [comment]
I'm also probably gonna be able to write some things Sunday. No promises but if I get gentoo going by today, I can dedicate some of sunday to fixing this.

**Comment by llitz** [comment]
@vifino I got the build for node-js lessc working (it pulls a ton of dependencies) but it does looks like the same as with clessc overall.

I have not created one for clessc (just manual testing). I think we could add clessc as a euse flag so we don't need to use the lessc version (not kidding, lessc pulls ins 40 deps)

**Comment by vifino** [comment]
@llitz Ah, good. I'll try to package/steal clessc and add it as a dep.

Finally found some much needed time. Set up a new Gentoo install.
Included a nodejs ebuild in the overlay now to get firefox building on libressl.

**Comment by garyemiller** [comment]
I'm stuck trying to install on Gentoo.  Where do I get a lessc that works for this ebuild?

**Comment by ppfeufer** [comment]
I think it should be this » ``dev-nodejs/less``

**Comment by vifino** [comment]
Since clessc doesn't seem to let Polychromatic build correctly, it'll have to be the nodejs version, I guess.

Could someone with access to a Gentoo machine PR a dev-nodejs/less ebuild in and make this depend on it?
Mine broke while travelling and it'll be a while until I can get it fixed.

**Comment by vifino** [comment]
Thanks to @ppfeufer, we now have a dev-node/less ebuild and the Polychromatic ebuild depends on it.
So, this issue should be fixed!

**Comment by garyemiller** [comment]
I just tried it and it failed.  Maybe still propagating to the portage servers?

**Comment by garyemiller** [comment]
How do I attach my build.log?  My desktop not setup for drag and drop.

dilbert /usr/local/src/GPS/gpsd # cat /tmp/app-misc\:polychromatic-9999\:20190120-003204.log 
 * Package:    app-misc/polychromatic-9999
 * Repository: vifino-overlay
 * Maintainer: vifino@tty.sh
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs userpriv usersandbox
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found sources for kernel version:
 *     4.20.3-gentoo
 * Checking for suitable kernel configuration options...                 [ ok ]
>>> Unpacking source...
 * Repository id: lah7_polychromatic.git
 * Fetching https://github.com/lah7/polychromatic.git ...
git fetch https://github.com/lah7/polychromatic.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/app-misc/polychromatic/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/lah7/polychromatic.git to /u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/lah7/polychromatic.git
   at the commit:            730bdb19fdae3d0e3c6b8d179de9d702362e19d0
>>> Source unpacked in /u1/tmp/portage/app-misc/polychromatic-9999/work
>>> Preparing source in /u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source prepared.
>>> Configuring source in /u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source configured.
>>> Compiling source in /u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source compiled.
>>> Test phase [not enabled]: app-misc/polychromatic-9999

>>> Install polychromatic-9999 into /u1/tmp/portage/app-misc/polychromatic-9999/image/ category app-misc
make -j4 PREFIX=/usr DESTDIR=/u1/tmp/portage/app-misc/polychromatic-9999/image/ install 
lessc source/data/controller.less data/pages/controller.css
make: lessc: Command not found
make: *** [Makefile:24: css] Error 127
 * ERROR: app-misc/polychromatic-9999::vifino-overlay failed (install phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-misc/polychromatic-9999::vifino-overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-misc/polychromatic-9999::vifino-overlay'`.
 * The complete build log is located at '/var/log/app-misc:polychromatic-9999:20190120-003204.log'.
 * For convenience, a symlink to the build log is located at '/u1/tmp/portage/app-misc/polychromatic-9999/temp/build.log'.
 * The ebuild environment file is located at '/u1/tmp/portage/app-misc/polychromatic-9999/temp/environment'.
 * Working directory: '/u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999'
 * S: '/u1/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999'

**Comment by ppfeufer** [comment]
» sync your overlays
» emerge it

I don't know if you use eix, but after syncing your overlays you can check if dev-nodejs/less is available wit ``eix dev-nodejs/less``

Output should be something like this...
```
ppfeufer@thor ~ $ eix dev-nodejs/less
[I] dev-nodejs/less [1]
     Verfügbare Versionen:   (~)2.7.1
     Installierte Versionen: 2.7.1(22:10:48 19.01.2019)
     Startseite:             http://lesscss.org/
     Beschreibung:           Leaner CSS

[1] "vifino-overlay" /var/lib/layman/vifino-overlay
```

**Comment by vifino** [comment]
No, it should be ok, but I think we might need to add dev-nodejs to /etc/portage/categories or rather make the overlay do this?
I'm really unsure, @ppfeufer, if you would be so kind, could you check the overlay where you got the ebuild from if it contains any category change, and if it does, can you propagate it to here as well?

**Comment by ppfeufer** [comment]
Oh ya, my fault. (First time I'm doing stuff like this)
New PR incoming

**Comment by vifino** [comment]
@ppfeufer No worries! Merged! 👍 
It should be fixed now, then. Anyone wanna confirm?

**Comment by vifino** [comment]
This has been fixed for a while now.
