### ISSUE TITLE
Update d2to1 ebuild to support python3.9

### ISSUE THREAD

**Issue by Kusoneko** [vifino/vifino-overlay#48]
Hello, polychromatic crashes consistently when using python3.9, mostly with an error stating that it couldn't import colour. Looking at dev-python/colour here, it targets python3.7, 3.8 and 3.9, however, when compiling that, that pulls in dev-python/d2to1 which is only available for python3.6, 3.7 and 3.8. This prevents colour from emerging, which in turns prevents polychromatic from running. I used to have the use flag "-python_targets_python3_9" in colour, however this is no longer practical since everything else has moved to 3.9, keeping that there causes the above error about the inability to import colour, it would be appreciated to update the d2to1 ebuild to support python3.9 if possible, otherwise, perhaps disable python3.9 on the other ebuilds so that they don't use python3.9?

**Comment by vifino** [comment]
Hey, apologies for the late response.
I just pushed a commit to have d2to1 also accept 3.9, it should work.
Please let me know if it works for you.

**Comment by Kusoneko** [comment]
It does, thanks!

**Comment by vifino** [comment]
Great! I'm glad. :)
