### ISSUE TITLE
erratic post-install behavior with app-misc/razer-drivers

### ISSUE THREAD

**Issue by thunderrd** [vifino/vifino-overlay#5]
Hi, I have a Blackwidow Ultimate 2016 on Gentoo.  After installing the driver and polychromatic [with the help of the other issue solved with nodejs and less], the driver seemed to work properly, only to lose its settings on reboot.  After reboot, the KB would not switch into 'Static' mode, the KB lighting completely out.  However, I could switch between some of the other states.

I struggled with this and the only way I could get 'Static' working again was a complete uninstall and reinstall of the driver, which also reinstalled polychromatic as well.  I referred to this page: https://github.com/openrazer/openrazer/wiki/Setting-up-the-keyboard-driver which had some useful information, but I suspect is indeed out of date, as it warns on the page.

I find that I can't predict the behavior of polychromatic; sometimes I can change the mode with it, and sometimes not.  [I think it's not the fault of polychromatic, though; I suspect I do not have the driver installed and loading correctly]

For the record, I really only want to 
a) set the keyboard to Static 
b) set the brightness to my preferred level
c) make it persistent across reboots, and
d) leave it at that.  

Ideally, I'd actually prefer to use only the driver without the front-end, making the changes directly in /sys/bus/hid/drivers/razerkbd

My use case is simple.

I believe that two drivers are being loaded; the razerkb.ko and the hid-generic, and I think this is causing the unpredictable behavior:

```
root@Q6600: ~# dmesg|grep Razer
[    1.487596] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.0/0003:1532:0214.0001/input/input5

[    1.572766] hid-generic 0003:1532:0214.0001: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input0

[    1.575894] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.1/0003:1532:0214.0002/input/input6

[    1.636310] hid-generic 0003:1532:0214.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input1

[    1.640572] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.2/0003:1532:0214.0003/input/input7

[    1.642493] hid-generic 0003:1532:0214.0003: input,hidraw2: USB HID v1.11 Mouse [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input2

[    3.191350] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.2/0003:1532:0214.0003/input/input9

[    3.356838] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.1/0003:1532:0214.0002/input/input10

[    3.556486] razerkbd 0003:1532:0214.0003: input,hidraw0: USB HID v1.11 Mouse [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input2

[    3.556727] input: Razer Razer BlackWidow Ultimate 2016 as /devices/pci0000:00/0000:00:1d.0/usb6/6-1/6-1:1.0/0003:1532:0214.0001/input/input11

[    3.626428] razerkbd 0003:1532:0214.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input1

[    3.696485] razerkbd 0003:1532:0214.0001: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:1d.0-1/input
```

Is this caused by a bind/unbind problem?  I can't figure out exactly how to tell if the KB is bound to the correct driver or not.

Sorry if this is elementary, but I'm new to this manually binding/unbinding procedure.

**Comment by vifino** [comment]
Hmm. I do not remember my setup loosing information, it remembered, I believe.
Unfortunately, I do not own any razer devices other than my Blade 14" and Core.

The kernel log (which I edited, slightly, to use a proper multiline code block)  seems to indicate that it did indeed bind to one of the inputs, which should be OK, as hid-generic is generic and razerkbd has a higher preference, I believe. Apart from that, you still need hid-generic for other things.

I am unsure what to do about this, but I believe a logical next step would be to ask the upstream guys, Terry Cain for example.

Unfortunately, I still don't have much time, so I can't promise to look more into it, as I can not reproduce it and for sure don't have the hardware for it.

**Comment by thunderrd** [comment]
OK, fair enough.  I'll look into it some more.  Thanks for the response.

**Comment by vifino** [comment]
No problem, always happy to help! Just have little time. :)

**Comment by vifino** [comment]
Did you ever figure out if it's an issue with packaging? I don't think so, but I don't wanna close an issue which might be my fault.

**Comment by thunderrd** [comment]
Not sure as yet, have to get some time to test with the new -9999 package.  So far, nothing has worked to get the daemon to start.

After I try the new package, I'll let you know what happens.
