### ISSUE TITLE
app-misc/razer-drivers should be renamed app-misc/openrazer

### ISSUE THREAD

**Issue by wschlich** [vifino/vifino-overlay#6]
See https://github.com/openrazer/openrazer/releases/tag/v2.0.0 for details :)

**Comment by vifino** [comment]
Hello.

I have to admit my noobness - I don't actually know how to rename an ebuild without breakage.

Renaming it is one thing, telling portage to use the new ebuild is another.

**Comment by vifino** [comment]
Slamming it in `profiles/updates/4Q-2017` should maybe work.

**Comment by vifino** [comment]
@wschlich Check out the `openrazer-rename` branch, I can not test right now.

**Comment by vifino** [comment]
@wschlich try again, please.

Added the ebuild for daemonize, never done python stuff before but it should work OK.

**Comment by vifino** [comment]
Don't have the hash for it, not at a gentoo machine right now. Might do it later.

**Comment by wschlich** [comment]
@vifino broken again, see my comment on 85104941d63bf54212398362e9a7227e8e1c7a69 :-)
