### ISSUE TITLE
Python 3.10 default update problems (PYTHON_COMPAT up to 3.9)

### ISSUE THREAD

**Issue by ashtophet** [vifino/vifino-overlay#67]
I'm using openrazer-9999 and polychromatic-9999 from your overlay (thanks for the fish!). As you may have experienced, from 2022/07/01 on Gentoo's default python version is 3.10, this causes a a bit of trouble with ebuilds with the upper limit of 3.9 -or less- for multiple versions via PYTHON_COMPAT.

I've solved it at my end with an unelegant `for i in */*/*.ebuild ; do sed -e 's/python3_{6\.\.9}/python3_{6\.\.10}/g' $i ; done`

Cheers

**Comment by ashtophet** [comment]
^sed -e^sed -i

**Comment by vifino** [comment]
Hey. I've committed changes that fix these problems.
You should be able to pull them either directly or wait a bit until the gentoo mirror bot picks it up.

**Comment by ashtophet** [comment]
Great! Thanks!
